name: Zola on GitHub Pages

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build only
        uses: wykies/zola-deploy-action@master
        env:
          OUT_DIR: docs
          BUILD_DIR: .
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy_prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build and deploy
        uses: wykies/zola-deploy-action@master
        env:
          OUT_DIR: docs
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy_test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build and deploy
        uses: wykies/zola-deploy-action@master
        env:
          OUT_DIR: docs
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages-test
          # REPOSITORY: wykies/web_test
          BUILD_FLAGS: --base-url https://wykies.github.io/web_test/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
